[package]
name = "circ"
version = "0.1.0"
authors = ["Alex Ozdemir <aozdemir@hmc.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hashconsing = { git = "https://github.com/alex-ozdemir/hashconsing" }
rug = "1.11"
fnv = "1.0.7"
lazy_static = "1.4"
rand = "0.8"
